### ISSUE TITLE
unhandled exception

### ISSUE THREAD

**Issue by rakuri255** [DidacticFishstick/ultrastar-wingman#4]
Nice App!

Got some exceptions with some songs. It seems that all songs with a `'` are affected.
Maybe UTF8 poblem?

```
[2023-12-26 02:36:44,041] INFO     werkzeug     Press CTRL+C to quit
Traceback (most recent call last):
  File "main.py", line 261, in <module>
  File "main.py", line 242, in main
  File "song.py", line 88, in load_songs
  File "song.py", line 245, in __init__
  File "song.py", line 225, in get_mp3_length
  File "eyed3\core.py", line 446, in load
OSError: file not found: F:\Games\UltraStar\UltraStar.Deluxe_v2023.12.0_portable\songs\Elvis Presley - Can’t Help Falling In Love_gpu\Elvis Presley - Canâ€™t Help Falling In Love [Instrumental].mp3
[8564] Failed to execute script 'main' due to unhandled exception!
```

**Comment by DidacticFishstick** [comment]
You were absolutely right. This was a problem with the txt files encoding. Some characters were ignored leading to a wrong path.
Thank you!

**Comment by rakuri255** [comment]
No, still not work.
PR #12 should fix that.
